### ISSUE TITLE
Error in rule simMaf

### ISSUE THREAD

**Issue by MarkKJF** [KarchinLab/2020plus#10]
I met some problem when running the code
$ snakemake -s Snakefile pretrained_predict -p --cores 1 \
     --config mutations="/home/kjf/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf" output_dir="output_bladder" trained_classifier="/home/kjf/data/2020plus_10k.Rdata"

The problem is
(2020plus) [kjf@localhost 2020plus-1.2.2]$ snakemake -s Snakefile pretrained_predict -p --cores 1 \
>      --config mutations="/home/kjf/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf" output_dir="output_bladder" trained_classifier="/home/kjf/data/2020plus_10k.Rdata"
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       features
        1       finishSim
        1       og
        1       predict_test
        1       pretrained_predict
        10      simFeatures
        10      simMaf
        10      simOg
        10      simSummary
        10      simTsg
        1       summary
        1       tsg
        57

[Sun Mar 31 14:20:18 2019]
rule simMaf:
    input: /home/kjf/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf
    output: output_bladder/simulated_summary/chasm_sim_maf1.txt
    jobid: 47
    wildcards: iter=1

mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5   -m /home/kjf/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf -p 0 -n 1 --maf --seed=$((1*42))   -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf1.txt
Traceback (most recent call last):
  File "/home/kjf/anaconda3/envs/2020plus/bin/mut_annotate", line 6, in <module>
    from prob2020.console.annotate import cli_main
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/site-packages/prob2020/console/annotate.py", line 12, in <module>
    import prob2020.cython.cutils as cutils
  File "numpy.pxd", line 861, in init prob2020.cython.cutils (prob2020/cython/cutils.cpp:19495)
ValueError: numpy.ufunc has the wrong size, try recompiling
[Sun Mar 31 14:20:19 2019]
Error in rule simMaf:
    jobid: 47
    output: output_bladder/simulated_summary/chasm_sim_maf1.txt

RuleException:
CalledProcessError in line 135 of /home/kjf/2020plus-1.2.2/Snakefile:
Command 'set -euo pipefail;  mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5   -m /home/kjf/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf -p 0 -n 1 --maf --seed=$((1*42))   -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf1.txt' returned non-zero exit status 1.
  File "/home/kjf/2020plus-1.2.2/Snakefile", line 135, in __rule_simMaf
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/kjf/2020plus-1.2.2/.snakemake/log/2019-03-31T142018.562491.snakemake.log

could you plz help with this?

**Comment by ctokheim** [comment]
Hi. Does this error only happen with your own custom mutation file ("TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf") or does it also happen with the example mutations for bladder carcinoma?

**Comment by ctokheim** [comment]
From the following thread on the scipy github repository, this might be due to you having multiple copies of numpy (https://github.com/scipy/scipy/issues/3448). Could you check if you have multiple numpy packages installed in various locations?

**Comment by MarkKJF** [comment]
I use "conda list" to check my packages and found this 
#############
numba                     0.39.0           py37h04863e7_0
numexpr                   2.6.8            py37hd89afb7_0
numpy                     1.15.1           py37h1d66e8a_0
numpy-base                1.15.1           py37h81de0dd_0
numpydoc                  0.8.0                    py37_0

should I remove the numpy or numpy-base ?

**Comment by ctokheim** [comment]
I'm not sure if this is your only python on your system (as there could be a numpy package in another conda environment or some system-level python). First thing you could check is whether uninstalling both and then reinstalling numpy helps

**Comment by MarkKJF** [comment]
Thanks for your help. I remove the numpy packages and install the package needed.
Now the question turns into this :data//snvboxGenes.fa` not found
I run the code $ extract_gene_seq -i hg19.fa -b snvboxGenes.bed -o snvboxGenes.fa
successfully in my data file and the .fa is already in my data file. But it still tells me the .fa file not found

(2020plus) [kjf@localhost 2020plus-1.2.2]$ snakemake -s Snakefile pretrained_predict -p --cores 1 \
>      --config mutations="/home/kjf/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf" output_dir="output_bladder" trained_classifier="/home/kjf/data/2020plus_10k.Rdata"
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       features
        1       finishSim
        1       og
        1       predict_test
        1       pretrained_predict
        10      simFeatures
        10      simMaf
        10      simOg
        10      simSummary
        10      simTsg
        1       summary
        1       tsg
        57

[Mon Apr  1 02:21:34 2019]
rule simMaf:
    input: /home/kjf/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf
    output: output_bladder/simulated_summary/chasm_sim_maf3.txt
    jobid: 49
    wildcards: iter=3

mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5   -m /home/kjf/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf -p 0 -n 1 --maf --seed=$((3*42))   -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf3.txt
Command: /home/kjf/anaconda3/envs/2020plus/bin/mut_annotate --log-level=INFO -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5 -m /home/kjf/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf -p 0 -n 1 --maf --seed=126 -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf3.txt
Traceback (most recent call last):
  File "/home/kjf/anaconda3/envs/2020plus/bin/mut_annotate", line 10, in <module>
    sys.exit(cli_main())
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/site-packages/prob2020/console/annotate.py", line 432, in cli_main
    main(opts)
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/site-packages/prob2020/console/annotate.py", line 380, in main
    gene_fa = pysam.Fastafile(opts['input'])
  File "pysam/libcfaidx.pyx", line 123, in pysam.libcfaidx.FastaFile.__cinit__
  File "pysam/libcfaidx.pyx", line 155, in pysam.libcfaidx.FastaFile._open
OSError: file `data//snvboxGenes.fa` not found
[Mon Apr  1 02:21:35 2019]
Error in rule simMaf:
    jobid: 49
    output: output_bladder/simulated_summary/chasm_sim_maf3.txt

RuleException:
CalledProcessError in line 135 of /home/kjf/2020plus-1.2.2/Snakefile:
Command 'set -euo pipefail;  mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5   -m /home/kjf/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf -p 0 -n 1 --maf --seed=$((3*42))   -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf3.txt' returned non-zero exit status 1.
  File "/home/kjf/2020plus-1.2.2/Snakefile", line 135, in __rule_simMaf
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/kjf/2020plus-1.2.2/.snakemake/log/2019-04-01T022134.609091.snakemake.log

**Comment by ctokheim** [comment]
I'm not quite sure which directory you are running snakemake from. Have you tried running snakemake from directly within the 2020plus-1.2.2 directory with the data folder as subdirectory that contains the .fa file?

**Comment by MarkKJF** [comment]
Thanks a lot. It works. I try to run snakemake from directly within the 2020plus-1.2.2 directory with the data folder as subdirectory that contains the .fa file. Now I meet a new problem: 
pandas.errors.ParserError: Error tokenizing data. C error:

(2020plus) [kjf@localhost 2020plus-1.2.2]$ snakemake -s Snakefile pretrained_predict -p --cores 1 \
>      --config mutations="/home/kjf/2020plus-1.2.2/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf" output_dir="output" trained_classifier="/home/kjf/2020plus-1.2.2/data/2020plus_10k.Rdata"
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       features
        1       finishSim
        1       og
        1       predict_test
        1       pretrained_predict
        10      simFeatures
        10      simMaf
        10      simOg
        10      simSummary
        10      simTsg
        1       summary
        1       tsg
        57

[Mon Apr  1 09:49:30 2019]
rule simSummary:
    input: /home/kjf/2020plus-1.2.2/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf
    output: output/simulated_summary/chasm_sim_summary8.txt
    jobid: 38
    wildcards: iter=8

mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa   -c 1.5 -m /home/kjf/2020plus-1.2.2/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf -p 0 -n 1 --summary --seed=$((8*42))   --score-dir=data//scores   --unique -r 3 -o output/simulated_summary/chasm_sim_summary8.txt
Command: /home/kjf/anaconda3/envs/2020plus/bin/mut_annotate --log-level=INFO -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5 -m /home/kjf/2020plus-1.2.2/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf -p 0 -n 1 --summary --seed=336 --score-dir=data//scores --unique -r 3 -o output/simulated_summary/chasm_sim_summary8.txt
Traceback (most recent call last):
  File "/home/kjf/anaconda3/envs/2020plus/bin/mut_annotate", line 10, in <module>
    sys.exit(cli_main())
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/site-packages/prob2020/console/annotate.py", line 432, in cli_main
    main(opts)
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/site-packages/prob2020/console/annotate.py", line 384, in main
    mut_df = pd.read_csv(opts['mutations'], sep='\t')
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/site-packages/pandas/io/parsers.py", line 1995, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 955, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 120

[Mon Apr  1 09:49:32 2019]
Error in rule simSummary:
    jobid: 38
    output: output/simulated_summary/chasm_sim_summary8.txt

RuleException:
CalledProcessError in line 152 of /home/kjf/2020plus-1.2.2/Snakefile:
Command 'set -euo pipefail;  mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa   -c 1.5 -m /home/kjf/2020plus-1.2.2/data/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf -p 0 -n 1 --summary --seed=$((8*42))   --score-dir=data//scores   --unique -r 3 -o output/simulated_summary/chasm_sim_summary8.txt' returned non-zero exit status 1.
  File "/home/kjf/2020plus-1.2.2/Snakefile", line 152, in __rule_simSummary
  File "/home/kjf/anaconda3/envs/2020plus/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/kjf/2020plus-1.2.2/.snakemake/log/2019-04-01T094930.721592.snakemake.log

**Comment by ctokheim** [comment]
I suspect your MAF file has meta information at the top (lines with "#" to start with). Please remove it. I also recommend that you run the example bladder MAF file first, instead of trying to provide your own MAF when doing initial testing.

**Comment by MarkKJF** [comment]
Thanks for you helpful support! I check MAF file and really find some "#". I will remove them.
However, I use the "bladder.txt" as the maf file. I run the coded
(2020plus) [kjf@localhost 2020plus-1.2.2]$ snakemake -s Snakefile pretrained_predict -p --cores 1 \
>      --config mutations="/home/kjf/2020plus-1.2.2/data/bladder.txt" output_dir="output" trained_classifier="/home/kjf/2020plus-1.2.2/data/2020plus_10k.Rdata"

and after more than an hour, it tells me that

Finished job 32.
1 of 57 steps (2%) done

I've stopped it now.
It seems that the code will takes more than 2 days? Is that normal?

**Comment by ctokheim** [comment]
I recommend running 20/20+ on a computer cluster to parallelize calculations. This should reduce the run time to about a couple of hours.

**Comment by MarkKJF** [comment]
Thanks but I don't have the computer cluster environment. 
Sorry for trouble you again and again.

Maybe I stop the proceed in a improper way. Now I try to run the code again it warns me that

Building DAG of jobs...
Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:
/home/kjf/2020plus-1.2.2
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be removed with the --unlock argument.

and I try to unlock it with $ snakemake --unlock

(2020plus) [kjf@localhost 2020plus-1.2.2]$ snakemake --unlock
Building DAG of jobs...
MissingInputException in line 220 of /home/kjf/2020plus-1.2.2/Snakefile:
Missing input files for rule summary:
data/mutations.txt

What's more, I am wondering if I can just increase the number after the --cores?
That is ,change
$ snakemake -s Snakefile pretrained_predict -p --cores 1 \
     --config mutations="/home/kjf/2020plus-1.2.2/data/bladder.txt" output_dir="output" trained_classifier="/home/kjf/2020plus-1.2.2/data/2020plus_10k.Rdata"

into

$ snakemake -s Snakefile pretrained_predict -p --cores 10 \
     --config mutations="/home/kjf/2020plus-1.2.2/data/bladder.txt" output_dir="output" trained_classifier="/home/kjf/2020plus-1.2.2/data/2020plus_10k.Rdata"

to increase the speed? 
Cause I am running the code on my laptop with windows system, using the Bitvise SSH Client to create a Linux operating environment.

Thanks for your time and patience again.

**Comment by ctokheim** [comment]
You can increase the number of cores being used through the `--cores` argument to increase speed. But be careful not to exceed how many threads your computer can use and be aware of RAM usage.

**Comment by ctokheim** [comment]
If you cut off the job in the middle, snakemake may not always exit gracefully (resulting in your above message)

**Comment by MarkKJF** [comment]
Thanks. So what should I do if I want to continue the work or restart it again?

**Comment by ctokheim** [comment]
Normally Snakemake will resume where you left off when there is an error. You run the same exact command for the restart. However, if you kill everything and don't let snakemake finish exiting then you probably end up where snakemake won't restart properly. You may have do delete the existing output or snakemake temporary files to resume. I encourage you to look into the snakemake documentation page for more details.

**Comment by MarkKJF** [comment]
Thank you very much. I can run the command again~
