### ISSUE TITLE
Can't open file 'features': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by AteeqMKhaliq** [KarchinLab/2020plus#14]
Hi, 
While running the program and under simFeatures creation, I am encountering the following error. please let me know what's the issue and how best it can be resolved.  
Thanks a lot for your kind help.

`snakemake -s Snakefile pretrained_predict -p --cores 1 --config mutations="data/soma_fb_2020_mod.txt" output_dir="output_soma_freebayes" trained_classifier="data/2020plus_10k.Rdata"

rule simFeatures:
    input: output_soma_freebayes/simulated_summary/chasm_sim_summary3.txt, output_soma_freebayes/simulated_summary/oncogene_sim3.txt, output_soma_freebayes/simulated_summary/tsg_sim3.txt
    output: output_soma_freebayes/simulated_summary/simulated_features3.txt
    jobid: 7
    wildcards: iter=3

python `which 2020plus.py` features   -s output_soma_freebayes/simulated_summary/chasm_sim_summary3.txt --tsg-test output_soma_freebayes/simulated_summary/tsg_sim3.txt -og-test output_soma_freebayes/simulated_summary/oncogene_sim3.txt   -o output_soma_freebayes/simulated_summary/simulated_features3.txt
which: no 2020plus.py in (/home/ateeqanees/anaconda3/bin:/home/ateeqanees/miniconda3/envs/2020plus/bin:/home/ateeqanees/miniconda3/condabin:/home/ateeqanees/anaconda3/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/ateeqanees/.local/bin:/home/ateeqanees/bin)
python: can't open file 'features': [Errno 2] No such file or directory
Error in job simFeatures while creating output file output_soma_freebayes/simulated_summary/simulated_features3.txt.
RuleException:
CalledProcessError in line 202 of /home/ateeqanees/Desktop/20_20/2020plus-1.2.2/Snakefile:
Command 'python `which 2020plus.py` features   -s output_soma_freebayes/simulated_summary/chasm_sim_summary3.txt --tsg-test output_soma_freebayes/simulated_summary/tsg_sim3.txt -og-test output_soma_freebayes/simulated_summary/oncogene_sim3.txt   -o output_soma_freebayes/simulated_summary/simulated_features3.txt' returned non-zero exit status 2.
  File "/home/ateeqanees/Desktop/20_20/2020plus-1.2.2/Snakefile", line 202, in __rule_simFeatures
  File "/home/ateeqanees/miniconda3/envs/2020plus/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
`

Thanks a lot for your help,
Dave

**Comment by ctokheim** [comment]
Hi Dave. I have provided an answer to you on Biostars (https://www.biostars.org/p/423501/). Let me know there whether it worked or not.

**Comment by AteeqMKhaliq** [comment]
Thanks a lot Collin, it worked like a Charm! 
Dave!
