### ISSUE TITLE
Error for /bin/bash: line 1: 227964 Segmentation fault  

### ISSUE THREAD

**Issue by edceeyuchen** [KarchinLab/2020plus#33]
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       features
        1       finishSim
        1       predict_test
        1       pretrained_predict
        10      simFeatures
        14

rule simFeatures:
    input: 669samples_coding_dupfromcase/simulated_summary/chasm_sim_summary6.txt, 669samples_coding_dupfromcase/simulated_summary/oncogene_sim6.txt, 669samples_coding_dupfromcase/simulated_summary/tsg_sim6.txt
    output: 669samples_coding_dupfromcase/simulated_summary/simulated_features6.txt
    jobid: 13
    wildcards: iter=6

python `which 2020plus.py` features   -s 669samples_coding_dupfromcase/simulated_summary/chasm_sim_summary6.txt --tsg-test 669samples_coding_dupfromcase/simulated_summary/tsg_sim6.txt -og-test 669samples_coding_dupfromcase/simulated_summary/oncogene_sim6.txt   -o 669samples_coding_dupfromcase/simulated_summary/simulated_features6.txt
Version: 1.2.3
Command: /share/home/luoylLab/zengyuchen/biosoft/src/2020plus-1.2.3/2020plus.py features -s 669samples_coding_dupfromcase/simulated_summary/chasm_sim_summary6.txt --tsg-test 669samples_coding_dupfromcase/simulated_summary/tsg_sim6.txt -og-test 669samples_coding_dupfromcase/simulated_summary/oncogene_sim6.txt -o 669samples_coding_dupfromcase/simulated_summary/simulated_features6.txt
/bin/bash: line 1: 227964 Segmentation fault      (core dumped) python `which 2020plus.py` features -s 669samples_coding_dupfromcase/simulated_summary/chasm_sim_summary6.txt --tsg-test 669samples_coding_dupfromcase/simulated_summary/tsg_sim6.txt -og-test 669samples_coding_dupfromcase/simulated_summary/oncogene_sim6.txt -o 669samples_coding_dupfromcase/simulated_summary/simulated_features6.txt
Error in job simFeatures while creating output file 669samples_coding_dupfromcase/simulated_summary/simulated_features6.txt.
RuleException:
CalledProcessError in line 202 of /share/home/luoylLab/zengyuchen/biosoft/2020plus-1.2.3/Snakefile:
Command 'python `which 2020plus.py` features   -s 669samples_coding_dupfromcase/simulated_summary/chasm_sim_summary6.txt --tsg-test 669samples_coding_dupfromcase/simulated_summary/tsg_sim6.txt -og-test 669samples_coding_dupfromcase/simulated_summary/oncogene_sim6.txt   -o 669samples_coding_dupfromcase/simulated_summary/simulated_features6.txt' returned non-zero exit status 139.
  File "/share/home/luoylLab/zengyuchen/biosoft/2020plus-1.2.3/Snakefile", line 202, in __rule_simFeatures
  File "/share/home/luoylLab/zengyuchen/.conda/envs/2020plus/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message

**Comment by ctokheim** [comment]
Could you perhaps see if there is a log file that is mentioned, and post the content of it here? It sounds like there was an installation issue, as a segmentation fault would only happen if one of the software dependencies was not compiled correctly.

**Comment by edceeyuchen** [comment]
> Could you perhaps see if there is a log file that is mentioned, and post the content of it here? It sounds like there was an installation issue, as a segmentation fault would only happen if one of the software dependencies was not compiled correctly.

Thank you for your reply! And I re-install it, it's works!
