### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by sigven** [KarchinLab/2020plus#5]
Hi,

Would it be possible to make a Docker image of 2020plus with all the necessary software dependencies? I am struggling hard to make it run successfully (although I seemed to have done this previously), and not really understanding which requirements are needed to make everything work.

Sigve

**Comment by ctokheim** [comment]
Hi Sigve,

I just checked and it appears that an API change in the latest scikit-learn library has broken some of the code. Have you tried on scikit-learn version 0.19.2, as I believe scikit-learn version 0.20.0 has broken the code. Also make sure the python version is 3.5+.

Collin

**Comment by ctokheim** [comment]
I have created new installation instructions through using [conda](https://conda.io/miniconda.html) that should fix the issues you were likely having (and related to my above point). The installation instructions are available on the [20/20+ website](https://2020plus.readthedocs.io/en/latest/installation.html). The install instructions have been tested to work on a clean Ubuntu distribution.

We will likely add a Docker image in the future, but it will not be done immediately.

**Comment by sigven** [comment]
Hi,
Thanks for making the conda instructions! Just tried it out, but getting an error when I run `conda env create -f environment_python.yml` (see below). Got any idea why this happens?

`gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sigven/anaconda3/envs/2020plus/include -arch x86_64 -I/Users/sigven/anaconda3/envs/2020plus/include -arch x86_64 -Iprob2020/cython/ -I/Users/sigven/anaconda3/envs/2020plus/lib/python3.6/site-packages/numpy/core/include -I/Users/sigven/anaconda3/envs/2020plus/include/python3.6m -c prob2020/cython/uniform_kde.cpp -o build/temp.macosx-10.7-x86_64-3.6/prob2020/cython/uniform_kde.o
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from prob2020/cython/uniform_kde.cpp:303:
    In file included from /Users/sigven/anaconda3/envs/2020plus/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/sigven/anaconda3/envs/2020plus/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /Users/sigven/anaconda3/envs/2020plus/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:
    /Users/sigven/anaconda3/envs/2020plus/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \`
     ^
    prob2020/cython/uniform_kde.cpp:306:10: fatal error: 'vector' file not found
    #include <vector>
             ^~~~~~~~
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
`Command "/Users/sigven/anaconda3/envs/2020plus/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kw/sbc71xm12cz18s24f1mvrzd00000gq/T/pip-install-eq24bpjj/probabilistic2020/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kw/sbc71xm12cz18s24f1mvrzd00000gq/T/pip-record-ca18s3am/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kw/sbc71xm12cz18s24f1mvrzd00000gq/T/pip-install-eq24bpjj/probabilistic2020/`

CondaValueError: pip returned an error

**Comment by ctokheim** [comment]
Are you trying to build it on mac os x? I would recommend a linux operating system if you can, as this is what 20/20+ is tested on.

**Comment by sigven** [comment]
Got it, will try asap. Thanks!

**Comment by sigven** [comment]
Hi again,

I have established an updated Docker image with your latest installation instructions using conda. 
https://github.com/sigven/2020plusDocker

I was running the example file (`bladder.txt`), but the job did not complete successfully:

`
Command: /usr/local/miniconda3/envs/2020plus/bin/mut_annotate --log-level=INFO -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5 -m /data/bladder.txt -p 0 -n 1 --maf --seed=336 -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf8.txt`
`There were 832 indels identified`.
`Kept 33771 mutations after droping mutations with missing information (Droped: 0)`
`Dropped 832 mutations after only keeping Missense_Mutation, Silent, Nonsense_Mutation, Splice_Site, Nonstop_Mutation, Translation_Start_Site. Indels are processed separately.`
`Dropped 182 mutations after only keeping valid SNVs`
`Dropped 0 mutations when removing duplicates`
`Working on chromosome: chr1 . . .`
`Finished working on chromosome: chr1.`
`Working on chromosome: chr19 . . .`
`Finished working on chromosome: chr19.`
`Working on chromosome: chr11 . . .`
`Finished working on chromosome: chr11.`
`Working on chromosome: chr2 . . .`
`Finished working on chromosome: chr2.`
`Working on chromosome: chr17 . . .`
`Finished working on chromosome: chr17.`
`Working on chromosome: chr3 . . .`
`Finished working on chromosome: chr3.`
`Working on chromosome: chr6 . . .`
`Finished working on chromosome: chr6.`
`Working on chromosome: chr12 . . .`
`Finished working on chromosome: chr12.`
`Working on chromosome: chr7 . . .`
`Killed`
`Error in job simMaf while creating output file output_bladder/simulated_summary/chasm_sim_maf8.txt.`
`RuleException:`
`CalledProcessError in line 135 of /2020plus/Snakefile:`
`Command 'mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5   -m /data/bladder.txt -p 0 -n 1 --maf --seed=$((8*42))   -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf8.txt' returned non-zero exit status 137.`
  `File "/2020plus/Snakefile", line 135, in __rule_simMaf`
`File "/usr/local/miniconda3/envs/2020plus/lib/python3.6/concurrent/futures/thread.py", line 56, in run`
`Removing output files of failed job simMaf since they might be corrupted:`
`output_bladder/simulated_summary/chasm_sim_maf8.txt`
`Will exit after finishing currently running jobs.`
`Exiting because a job execution failed. Look above for error message`

Have any idea what happened?

Sigve

**Comment by ctokheim** [comment]
I suspect that this likely relates to the resource constraint you have for your running Docker. My guess is that the line saying "Killed" is coming from Docker (https://stackoverflow.com/questions/44417159/docker-process-killed-with-cryptic-killed-message). You may want to expand the memory or go to a linux computer cluster where the machines have more memory.

**Comment by ctokheim** [comment]
I am closing the issue, as it may be resolved. Let me know if you still have issues, in which case I can reopen it.
