### ISSUE TITLE
pandas.errors.EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by sigven** [KarchinLab/2020plus#7]
Hi,

I am receiving the following error during my run:

`probabilistic2020 --log-level=INFO oncogene   -c 1.5 -n 10000 -b data//snvboxGenes.bed   -m output_fl/simulated_summary/chasm_sim_maf1.txt -i data//snvboxGenes.fa -p 4   --score-dir=data//scores -r 3   -o output_fl/simulated_summary/oncogene_sim1.txt`
`Version: 1.2.0`
`Command: /cluster/home/sigven/SOFTWARE/2020plus/bin/bin/probabilistic2020 --log-level=INFO oncogene -c 1.5 -n 10000 -b data//snvboxGenes.bed -m output_fl/simulated_summary/chasm_sim_maf1.txt -i data//snvboxGenes.fa -p 4 --score-dir=data//scores -r 3 -o output_fl/simulated_summary/oncogene_sim1.txt`
`Traceback (most recent call last):`
  `File "/cluster/home/sigven/SOFTWARE/2020plus/bin/bin/probabilistic2020", line 11, in <module>`
       `sys.exit(cli_main())`
  `File "/usit/abel/u1/sigven/SOFTWARE/2020plus/lib/python3.6/site-packages/prob2020/console/probabilistic2020.py", line 284, in cli_main`
       `main(opts)`
  `File "/usit/abel/u1/sigven/SOFTWARE/2020plus/lib/python3.6/site-packages/prob2020/console/probabilistic2020.py", line 229, in main`
       `result_df = rt.main(opts, mutation_df)`
 ` File "/usit/abel/u1/sigven/SOFTWARE/2020plus/lib/python3.6/site-packages/prob2020/console/randomization_test.py", line 366, in main`
       `mut_df = pd.read_csv(opts['mutations'], sep='\t')`
  `File "/usit/abel/u1/sigven/anaconda2/envs/2020plus/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f`
       `return _read(filepath_or_buffer, kwds)`
  `File "/usit/abel/u1/sigven/anaconda2/envs/2020plus/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read`
       `parser = TextFileReader(filepath_or_buffer, **kwds)`
  `File "/usit/abel/u1/sigven/anaconda2/envs/2020plus/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__`
       `self._make_engine(self.engine)`
  `File "/usit/abel/u1/sigven/anaconda2/envs/2020plus/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine`
       `self._engine = CParserWrapper(self.f, **self.options)`
  `File "/usit/abel/u1/sigven/anaconda2/envs/2020plus/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__`
       `self._reader = parsers.TextReader(src, **kwds)`
  `File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__`
`pandas.errors.EmptyDataError: No columns to parse from file`
Error in job simOg while creating output file output_fl/simulated_summary/oncogene_sim1.txt.

Do you have any clue of what's going wrong?

**Comment by ctokheim** [comment]
I suspect that the job creating `output_fl/simulated_summary/chasm_sim_maf1.txt` must have failed or created an empty file. Is this file empty? If you remove the empty file and try to rerun then I think it should work.

**Comment by sigven** [comment]
Thanks, it seems to run again. Not sure what happened, will see how it goes.

**Comment by ctokheim** [comment]
On a computer cluster, I recommend adding a long latency wait for snakemake. This will make it more likely that snakemake won't try to proceed to the next job before the previous one has written the full output file. You can specify the latency wait in snakemake by the `-w` parameter (specified in seconds). Something like `-w 1000` will give it plenty of time. I don't know if this is the exact case for you, but it seems likely.

**Comment by sigven** [comment]
Thanks again for your rapid feedback when running into problems. Highly appreciated. 

Successful run now:-)

Kind regards,
Sigve

**Comment by ctokheim** [comment]
Great!
