### ISSUE TITLE
OSError: file `data//snvboxGenes.fa` not found

### ISSUE THREAD

**Issue by sandaru** [KarchinLab/2020plus#8]
I'm getting and error while executing following sample command 

snakemake -s Snakefile pretrained_predict -p --cores 1 --config mutations="data/bladder.txt" output_dir="output_bladder" trained_classifier="data/2020plus_10k.Rdata" 

ERROR

Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	features
	1	finishSim
	1	og
	1	predict_test
	1	pretrained_predict
	10	simFeatures
	10	simMaf
	10	simOg
	10	simSummary
	10	simTsg
	1	summary
	1	tsg
	57

rule simMaf:
    input: data/bladder.txt
    output: output_bladder/simulated_summary/chasm_sim_maf5.txt
    jobid: 51
    wildcards: iter=5

mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5   -m data/bladder.txt -p 0 -n 1 --maf --seed=$((5*42))   -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf5.txt
Command: /root/Desktop/2020_Prod/2020plus/2020plus/bin/mut_annotate --log-level=INFO -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5 -m data/bladder.txt -p 0 -n 1 --maf --seed=210 -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf5.txt
Traceback (most recent call last):
  File "/root/Desktop/2020_Prod/2020plus/2020plus/bin/mut_annotate", line 10, in <module>
    sys.exit(cli_main())
  File "/root/Desktop/2020_Prod/2020plus/2020plus/lib/python3.6/site-packages/prob2020/console/annotate.py", line 432, in cli_main
    main(opts)
  File "/root/Desktop/2020_Prod/2020plus/2020plus/lib/python3.6/site-packages/prob2020/console/annotate.py", line 380, in main
    gene_fa = pysam.Fastafile(opts['input'])
  File "pysam/libcfaidx.pyx", line 123, in pysam.libcfaidx.FastaFile.__cinit__
  File "pysam/libcfaidx.pyx", line 155, in pysam.libcfaidx.FastaFile._open
OSError: file `data//snvboxGenes.fa` not found
Error in job simMaf while creating output file output_bladder/simulated_summary/chasm_sim_maf5.txt.
RuleException:
CalledProcessError in line 135 of /root/Desktop/2020_Prod/2020plus/Snakefile:
Command 'mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5   -m data/bladder.txt -p 0 -n 1 --maf --seed=$((5*42))   -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf5.txt' returned non-zero exit status 1.
  File "/root/Desktop/2020_Prod/2020plus/Snakefile", line 135, in __rule_simMaf
  File "/root/Desktop/2020_Prod/2020plus/2020plus/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message

**Comment by sandaru** [comment]
I followed the procedure mentioned in following document
https://2020plus.readthedocs.io/en/latest/tutorial.html#tut-ref

after extracting everything, I found a file call snvboxGenes.bed. But there wasn't a file named "snvboxGenes.fa"

Please help me.

Thanks,
/Sandaru

**Comment by ctokheim** [comment]
You skipped a step in the tutorial. Please see the step on creating a fasta file: https://probabilistic2020.readthedocs.io/en/latest/tutorial.html#gene-fasta

**Comment by sandaru** [comment]
Thanks for the help. Yes I missed it

**Comment by adnanakbr** [comment]
do we have to create our own bed file using SVNBox for our data or the svnboxGenes.fa contains data for all genes?

**Comment by ctokheim** [comment]
It contains data for all protein coding genes. So you shouldn't have to use a custom BED file.
