### ISSUE TITLE
Keep getting error : Error in job simMaf while creating output file 

### ISSUE THREAD

**Issue by sandaru** [KarchinLab/2020plus#9]
Hi I'm getting following error while executing sample files. I couldn't find any fix for this. Can you please help on this

ERROR:

snakemake -s Snakefile pretrained_predict -p --cores 1 \
>      --config mutations="data/bladder.txt" output_dir="output_bladder" trained_classifier="data/2020plus_10k.Rdata"
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	features
	1	finishSim
	1	og
	1	predict_test
	1	pretrained_predict
	10	simFeatures
	10	simMaf
	10	simOg
	10	simSummary
	10	simTsg
	1	summary
	1	tsg
	57

rule simMaf:
    input: data/bladder.txt
    output: output_bladder/simulated_summary/chasm_sim_maf3.txt
    jobid: 50
    wildcards: iter=3

mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5   -m data/bladder.txt -p 0 -n 1 --maf --seed=$((3*42))   -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf3.txt
Command: /root/miniconda3/envs/2020plus/bin/mut_annotate --log-level=INFO -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5 -m data/bladder.txt -p 0 -n 1 --maf --seed=126 -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf3.txt
There were 832 indels identified.
Kept 33771 mutations after droping mutations with missing information (Droped: 0)
Dropped 832 mutations after only keeping Missense_Mutation, Silent, Nonsense_Mutation, Splice_Site, Nonstop_Mutation, Translation_Start_Site. Indels are processed separately.
Dropped 182 mutations after only keeping valid SNVs
Dropped 0 mutations when removing duplicates
Working on chromosome: chr1 . . .
Finished working on chromosome: chr1.
Working on chromosome: chr19 . . .
Finished working on chromosome: chr19.
Working on chromosome: chr11 . . .
Finished working on chromosome: chr11.
Working on chromosome: chr2 . . .
Finished working on chromosome: chr2.
Working on chromosome: chr17 . . .
Finished working on chromosome: chr17.
Working on chromosome: chr3 . . .
Finished working on chromosome: chr3.
Working on chromosome: chr6 . . .
Finished working on chromosome: chr6.
Working on chromosome: chr12 . . .
Finished working on chromosome: chr12.
Working on chromosome: chr7 . . .
Finished working on chromosome: chr7.
Working on chromosome: chr5 . . .
Finished working on chromosome: chr5.
Working on chromosome: chr14 . . .
Finished working on chromosome: chr14.
Working on chromosome: chr16 . . .
Finished working on chromosome: chr16.
Working on chromosome: chr9 . . .
Finished working on chromosome: chr9.
Working on chromosome: chrX . . .
Finished working on chromosome: chrX.
Working on chromosome: chr10 . . .
Finished working on chromosome: chr10.
Working on chromosome: chr4 . . .
Finished working on chromosome: chr4.
Working on chromosome: chr8 . . .
Finished working on chromosome: chr8.
Working on chromosome: chr15 . . .
Finished working on chromosome: chr15.
Working on chromosome: chr20 . . .
Finished working on chromosome: chr20.
Working on chromosome: chr22 . . .
Finished working on chromosome: chr22.
Working on chromosome: chr13 . . .
Finished working on chromosome: chr13.
Working on chromosome: chr18 . . .
Finished working on chromosome: chr18.
Working on chromosome: chr21 . . .
Finished working on chromosome: chr21.
Working on chromosome: chrY . . .
Finished working on chromosome: chrY.
Working on chromosome: chrM . . .
Finished working on chromosome: chrM.
/bin/bash: line 1: 11394 Killed                  mut_annotate --log-level=INFO -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5 -m data/bladder.txt -p 0 -n 1 --maf --seed=$((3*42)) -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf3.txt
**Error in job simMaf while creating output file output_bladder/simulated_summary/chasm_sim_maf3.txt.
RuleException:
CalledProcessError in line 135 of /root/Desktop/2020_Prod/2020plus-1.2.2/Snakefile:
Command 'mut_annotate --log-level=INFO    -b data//snvboxGenes.bed -i data//snvboxGenes.fa -c 1.5   -m data/bladder.txt -p 0 -n 1 --maf --seed=$((3*42))   -r 3 --unique -o output_bladder/simulated_summary/chasm_sim_maf3.txt' returned non-zero exit status 137.
  File "/root/Desktop/2020_Prod/2020plus-1.2.2/Snakefile", line 135, in __rule_simMaf
  File "/root/miniconda3/envs/2020plus/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job simMaf since they might be corrupted:
output_bladder/simulated_summary/chasm_sim_maf3.txt
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message**

**Comment by ctokheim** [comment]
Hi. Based on "/bin/bash: line 1: 11394 Killed" in the error message, I suspect that 20/20+ exceeded your computer resources, such as memory or something else, and this resulted in the operating system killing the job. Are you running 20/20+ inside a virtual machine with limited resources? Regardless, it may be better to run 20/20+ on a computer cluster which has more resources.
